# Generated by Django 4.0.6 on 2022-11-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram',
            name='session_token',
            field=models.TextField(default=False),
        ),
    ]
